import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const montserrat = localFont({
  src: "./fonts/Montserrat-VariableFont.ttf",
  variable: "--font-montserrat",
  weight: "100 900",
});

const roboto = localFont({
  src: [
    {
      path: "./fonts/Roboto-Regular.ttf",
      weight: "400", // Regular weight
      style: "normal",
    },
    {
      path: "./fonts/Roboto-Medium.ttf",
      weight: "500", // Italic
      style: "normal",
    },
    {
      path: "./fonts/Roboto-Bold.ttf",
      weight: "700", // Bold weight
      style: "normal",
    }
  ],
  variable: "--font-roboto", // Custom CSS variable for the font
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-app-background text-color ${montserrat.variable} ${roboto.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
